import type { RefusalScene } from "./refusals";
import data from "./refusals-data.json";

// Build-time output of getRefusalScenes() (real Cedar denials), regenerated by
// `pnpm gen:refusals` and kept honest by refusals-data.test.ts. The page imports
// this instead of evaluating Cedar in the Next runtime, so it stays static and
// ships no WASM.
export const refusalScenes = data as unknown as RefusalScene[];
