import type { TenantProof } from "./tenants";
import data from "./tenants-data.json";

// Build-time output of getTenantProof() (real Cedar decisions through policy 07),
// regenerated by `pnpm gen:tenants` and kept honest by tenants-data.test.ts. The
// page imports this instead of evaluating Cedar in the Next runtime, so it stays
// static and ships no WASM.
export const tenantProof = data as unknown as TenantProof;
